/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WasteLogRouteImport } from './routes/waste-log'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as VarianceRouteImport } from './routes/variance'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as SegmentsRouteImport } from './routes/segments'
import { Route as SchedulingRouteImport } from './routes/scheduling'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as ProductMixRouteImport } from './routes/product-mix'
import { Route as PnlRouteImport } from './routes/pnl'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaborRouteImport } from './routes/labor'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InventoryVarianceRouteImport } from './routes/inventory-variance'
import { Route as InventoryCountRouteImport } from './routes/inventory-count'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as IngredientPriceTrendsRouteImport } from './routes/ingredient-price-trends'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const WasteLogRoute = WasteLogRouteImport.update({
  id: '/waste-log',
  path: '/waste-log',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const VarianceRoute = VarianceRouteImport.update({
  id: '/variance',
  path: '/variance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentsRoute = SegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingRoute = SchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductMixRoute = ProductMixRouteImport.update({
  id: '/product-mix',
  path: '/product-mix',
  getParentRoute: () => rootRouteImport,
} as any)
const PnlRoute = PnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaborRoute = LaborRouteImport.update({
  id: '/labor',
  path: '/labor',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryVarianceRoute = InventoryVarianceRouteImport.update({
  id: '/inventory-variance',
  path: '/inventory-variance',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryCountRoute = InventoryCountRouteImport.update({
  id: '/inventory-count',
  path: '/inventory-count',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientPriceTrendsRoute = IngredientPriceTrendsRouteImport.update({
  id: '/ingredient-price-trends',
  path: '/ingredient-price-trends',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ingredient-price-trends': typeof IngredientPriceTrendsRoute
  '/inventory': typeof InventoryRoute
  '/inventory-count': typeof InventoryCountRoute
  '/inventory-variance': typeof InventoryVarianceRoute
  '/invoices': typeof InvoicesRoute
  '/labor': typeof LaborRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/marketing': typeof MarketingRoute
  '/pnl': typeof PnlRoute
  '/product-mix': typeof ProductMixRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/recipes': typeof RecipesRoute
  '/reviews': typeof ReviewsRoute
  '/scheduling': typeof SchedulingRoute
  '/segments': typeof SegmentsRoute
  '/seo': typeof SeoRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/variance': typeof VarianceRoute
  '/vendors': typeof VendorsRoute
  '/waste-log': typeof WasteLogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ingredient-price-trends': typeof IngredientPriceTrendsRoute
  '/inventory': typeof InventoryRoute
  '/inventory-count': typeof InventoryCountRoute
  '/inventory-variance': typeof InventoryVarianceRoute
  '/invoices': typeof InvoicesRoute
  '/labor': typeof LaborRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/marketing': typeof MarketingRoute
  '/pnl': typeof PnlRoute
  '/product-mix': typeof ProductMixRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/recipes': typeof RecipesRoute
  '/reviews': typeof ReviewsRoute
  '/scheduling': typeof SchedulingRoute
  '/segments': typeof SegmentsRoute
  '/seo': typeof SeoRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/variance': typeof VarianceRoute
  '/vendors': typeof VendorsRoute
  '/waste-log': typeof WasteLogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ingredient-price-trends': typeof IngredientPriceTrendsRoute
  '/inventory': typeof InventoryRoute
  '/inventory-count': typeof InventoryCountRoute
  '/inventory-variance': typeof InventoryVarianceRoute
  '/invoices': typeof InvoicesRoute
  '/labor': typeof LaborRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/marketing': typeof MarketingRoute
  '/pnl': typeof PnlRoute
  '/product-mix': typeof ProductMixRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/recipes': typeof RecipesRoute
  '/reviews': typeof ReviewsRoute
  '/scheduling': typeof SchedulingRoute
  '/segments': typeof SegmentsRoute
  '/seo': typeof SeoRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/variance': typeof VarianceRoute
  '/vendors': typeof VendorsRoute
  '/waste-log': typeof WasteLogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ingredient-price-trends'
    | '/inventory'
    | '/inventory-count'
    | '/inventory-variance'
    | '/invoices'
    | '/labor'
    | '/login'
    | '/loyalty'
    | '/marketing'
    | '/pnl'
    | '/product-mix'
    | '/purchase-orders'
    | '/recipes'
    | '/reviews'
    | '/scheduling'
    | '/segments'
    | '/seo'
    | '/set-password'
    | '/settings'
    | '/variance'
    | '/vendors'
    | '/waste-log'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ingredient-price-trends'
    | '/inventory'
    | '/inventory-count'
    | '/inventory-variance'
    | '/invoices'
    | '/labor'
    | '/login'
    | '/loyalty'
    | '/marketing'
    | '/pnl'
    | '/product-mix'
    | '/purchase-orders'
    | '/recipes'
    | '/reviews'
    | '/scheduling'
    | '/segments'
    | '/seo'
    | '/set-password'
    | '/settings'
    | '/variance'
    | '/vendors'
    | '/waste-log'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ingredient-price-trends'
    | '/inventory'
    | '/inventory-count'
    | '/inventory-variance'
    | '/invoices'
    | '/labor'
    | '/login'
    | '/loyalty'
    | '/marketing'
    | '/pnl'
    | '/product-mix'
    | '/purchase-orders'
    | '/recipes'
    | '/reviews'
    | '/scheduling'
    | '/segments'
    | '/seo'
    | '/set-password'
    | '/settings'
    | '/variance'
    | '/vendors'
    | '/waste-log'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  IngredientPriceTrendsRoute: typeof IngredientPriceTrendsRoute
  InventoryRoute: typeof InventoryRoute
  InventoryCountRoute: typeof InventoryCountRoute
  InventoryVarianceRoute: typeof InventoryVarianceRoute
  InvoicesRoute: typeof InvoicesRoute
  LaborRoute: typeof LaborRoute
  LoginRoute: typeof LoginRoute
  LoyaltyRoute: typeof LoyaltyRoute
  MarketingRoute: typeof MarketingRoute
  PnlRoute: typeof PnlRoute
  ProductMixRoute: typeof ProductMixRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  RecipesRoute: typeof RecipesRoute
  ReviewsRoute: typeof ReviewsRoute
  SchedulingRoute: typeof SchedulingRoute
  SegmentsRoute: typeof SegmentsRoute
  SeoRoute: typeof SeoRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  VarianceRoute: typeof VarianceRoute
  VendorsRoute: typeof VendorsRoute
  WasteLogRoute: typeof WasteLogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waste-log': {
      id: '/waste-log'
      path: '/waste-log'
      fullPath: '/waste-log'
      preLoaderRoute: typeof WasteLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variance': {
      id: '/variance'
      path: '/variance'
      fullPath: '/variance'
      preLoaderRoute: typeof VarianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segments': {
      id: '/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof SegmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling': {
      id: '/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof SchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-mix': {
      id: '/product-mix'
      path: '/product-mix'
      fullPath: '/product-mix'
      preLoaderRoute: typeof ProductMixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pnl': {
      id: '/pnl'
      path: '/pnl'
      fullPath: '/pnl'
      preLoaderRoute: typeof PnlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labor': {
      id: '/labor'
      path: '/labor'
      fullPath: '/labor'
      preLoaderRoute: typeof LaborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-variance': {
      id: '/inventory-variance'
      path: '/inventory-variance'
      fullPath: '/inventory-variance'
      preLoaderRoute: typeof InventoryVarianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-count': {
      id: '/inventory-count'
      path: '/inventory-count'
      fullPath: '/inventory-count'
      preLoaderRoute: typeof InventoryCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredient-price-trends': {
      id: '/ingredient-price-trends'
      path: '/ingredient-price-trends'
      fullPath: '/ingredient-price-trends'
      preLoaderRoute: typeof IngredientPriceTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  IngredientPriceTrendsRoute: IngredientPriceTrendsRoute,
  InventoryRoute: InventoryRoute,
  InventoryCountRoute: InventoryCountRoute,
  InventoryVarianceRoute: InventoryVarianceRoute,
  InvoicesRoute: InvoicesRoute,
  LaborRoute: LaborRoute,
  LoginRoute: LoginRoute,
  LoyaltyRoute: LoyaltyRoute,
  MarketingRoute: MarketingRoute,
  PnlRoute: PnlRoute,
  ProductMixRoute: ProductMixRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  RecipesRoute: RecipesRoute,
  ReviewsRoute: ReviewsRoute,
  SchedulingRoute: SchedulingRoute,
  SegmentsRoute: SegmentsRoute,
  SeoRoute: SeoRoute,
  SetPasswordRoute: SetPasswordRoute,
  SettingsRoute: SettingsRoute,
  VarianceRoute: VarianceRoute,
  VendorsRoute: VendorsRoute,
  WasteLogRoute: WasteLogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
